### ISSUE TITLE
jQuery Bağımlılığı

### ISSUE THREAD

**Issue by dnomak** [dnomak/svg-turkiye-haritasi#11]
Haritayı jQuery bağımlılığından kurtar :)

**Comment by fatiherikli** [comment]
#12

**Comment by d0ruk** [comment]
Merhaba,

Repo'yu klonlayıp index.html'i serve ettiğimde gördüğüm uygulama, http://dnomak.com/svg-turkiye-haritasi adresindeki demodan farklı.

index.html'e jQuery için <script> tag'i koymak gerekiyor. Zira bu da jQuery dependency'den tamamen arındırmıyor projeyi.
