### ISSUE TITLE
Su Rengi Belirleme

### ISSUE THREAD

**Issue by gguney** [dnomak/svg-turkiye-haritasi#19]
Merhabalar, 

Öncelikle elinize sağlık çok pratik olmuş. Yalnız, suların rengini de belirleyecek şekilde bir eklenti olabilir mi? Henüz bunun ile ilgili bir şey göremedim. Bazı alanları pasif yapmak adına kendim CSS ekledim fakat sular ile ilgili bir şey göremedim.

Şimdiden teşekkürler.

**Comment by suatsuphi** [comment]
illerin içinde il isimlerini nasıl gösterebiliriz ? mouse over güzel ancak il isimlerini de göstermek mümkün mü
