### ISSUE TITLE
il isimleri nasıl gösterilir

### ISSUE THREAD

**Issue by suatsuphi** [dnomak/svg-turkiye-haritasi#21]
Merhaba,

illerin içinde il isimlerini nasıl gösterebiliriz ? mouse over güzel ancak il isimlerini de göstermek mümkün mü?

**Comment by SarperMUTLUBAY** [comment]
Çalışma yapılarak yapılabilecek bir şey ancak yüz ölçümü bakımından büyük illerde sorun olmasa da Osmaniye veya Kilis gibi bir ilin içinde isim göstermek görsellik açısından kötü duracaktır.

![image](https://user-images.githubusercontent.com/10811371/40575534-4c4f3748-60ef-11e8-8ef2-1f9efaec341b.png)

**Comment by suatsuphi** [comment]
ben yaptım güzel oldu java konusunda bilgili değilim ancak svg dosyası text özelliğinin tasarıma gerek bırakmıyor. Kahramanmaraş ismi dediğiniz gibi sorun oldu onu da ikiye böldüm... ancak harita küçüldüğünde yazılar da küçülür bence güzel oldu. Kodlar aşağıda bu haritayı ücretli satan siteler var kıbrıs ta dahil değildi... 


https://drive.google.com/file/d/12wAJCx6AhiwV19S_v0pHYP5THA9k-1Q3/view?usp=sharing 

text tag ını path tagından sonraya koyarsam text tagının mouseover özelliği ortaya çıkıyor o yüzden text tagını önceye koydum ve  path transparency özelliğini kullanarak text i yazısını gösteriyorum. aksi durumda text mouseover ile path mouseover nasıl tetiklenir ? örnekte adana

**Comment by suatsuphi** [comment]
dosyayı bir div içine koyduuğunuzda div pozisyonunu ayarlanan tooltip pozisyonundan çıkartırlması gerekli.

element.addEventListener(
                'mousemove',
                function (event) {
                    var x = $("#turkiye").position().left;
                    var y = $("#turkiye").position().top;
                    info.style.top = event.pageY + 25 - y + 'px';
                    info.style.left = event.pageX - x + 'px';
                }
            );

**Comment by mehmetalikus** [comment]
sayfa uzunluğu yükseldikçe il isimleri gözükmüyor malesef. Şimdilik belli sabit bir değer verdim % lik bu sayede haritanın ortasında il isimleri çıkartabiliyorum. Kendine ait sadece harita sayfasında illerin üstünde çıkartıyorum. Bunu çözebilecek bi dahi var mı ?
