### ISSUE TITLE
Kent üzerinde il isminnin olması

### ISSUE THREAD

**Issue by barisgul** [dnomak/svg-turkiye-haritasi#26]
Merhaba,
Tüm şehirlerin üzerine şehir adını statik olarak nasıl yazdırabiliriz?

**Comment by SarperMUTLUBAY** [comment]
Merhaba,
Ne yazık ki şu an için öyle bir desteğı yok haritanın, desteği olsa dahi küçük illerde sorun olacaktır. Örneğin Kilis'in üzerine adını yazabilecek kadar bile alan bulunmuyor.
