### ISSUE TITLE
in Istanbul, asya and avrupa links are opposite links

### ISSUE THREAD

**Issue by arslanbilal** [dnomak/svg-turkiye-haritasi#3]
when tap istanbul(asya) -> http://dnomak.com/istanbul-avrupa-34.html
when tap istanbul(avrupa) http://dnomak.com/istanbul-asya-34.html

**Comment by dnomak** [comment]
neden kapattın :)

**Comment by arslanbilal** [comment]
Düzeltilmiş olarak görüyorum. Düzelmedi mi acaba?

**Comment by dnomak** [comment]
sayfaların hiçbiri açılmıyor tıklayınca hata veriyor o doğru ama asya avrupa yazımı karışmıştı onu düzelttim.

**Comment by arslanbilal** [comment]
Ben de düzeldi diye kapattım. Artık bir issue değil :)
