### ISSUE TITLE
Adalar - İl gösterimi

### ISSUE THREAD

**Issue by tayfunulu** [dnomak/svg-turkiye-haritasi#4]
- Çanakkale, İstanbul Asya ve Balıkesir'de adalar seçildiğinde sadece adaların rengi değişiyor. Bu yüzden yanlış bir bilgilendirme oluyor. Ada seçildiğinde bağlı olduğu ana karanın da renginin değişmesi gerekir.

**Comment by dnomak** [comment]
teşekkürler :+1:

**Comment by ahmtaras** [comment]
@tayfunulu 

https://www.dropbox.com/s/ev14pg9zltin7s1/svg-turkiye-haritasi.zip?dl=0

Pathleri birleştirerek yapabilirsiniz. Bir örnek attım.

**Comment by dnomak** [comment]
@ahmtaras bu repoya pull requests açarsan süper olur :)
