### ISSUE TITLE
Internet Explorer Desteği

### ISSUE THREAD

**Issue by imokkali** [dnomak/svg-turkiye-haritasi#6]
Internet Explorer 11 kullanıyorum. Harita küçük çıkıyor.

**Comment by dnomak** [comment]
svg elementine width: 100% vermek gerekiyor sanırım uygun zamanda test edip tekrar yazıcam teşekkürler :)

**Comment by imokkali** [comment]
Ben teşekkür ederim, dediğinizi yanlış uygulamadıysam denedim ama olmadı. İyi çalışmalar. :)

**Comment by SarperMUTLUBAY** [comment]
@imokkali id="svg-turkiye-haritasi" olan svg elementinin height değerini auto'dan manuel pixel bazlı kendin verirsen sorun giderilecektir bilgin olsun :)

**Comment by dnomak** [comment]
teşekkürler sarper :)

**Comment by imokkali** [comment]
Teşekkür ederim Sarper yardımın için onu denemiştim ben fakat bu sefer Responsive özelliğinde bozulma oluyor :( Harita düzgün küçülüyor fakat yukarısındaki ve aşağısındaki boşluklar orantısız oluyor.

**Comment by SarperMUTLUBAY** [comment]
onlar için de yine svg stilleriyle düzenleme yapabilirsin, geçen senin testi yaparken ben denk gelmiştim ona ama hangisi şu an hatırlamıyorum :)

**Comment by suatsuphi** [comment]
#svg-turkiye-haritasi {
  max-width: 1140px;
  margin: 0 auto;
  text-align: center;
  height:250px;/*buradan istediğin yüksekliğe göre ayarlama yapılıyor */
}
#svg-turkiye-haritasi svg {
  width: 100%;
  height:100%;
}

css de bunu deneyin düzgün çalışıyor yükseklikle harita ayarlanabiliyor. explorer ve chrome da sorun yok

**Comment by suatsuphi** [comment]
il isimleri direkt olarak "da" yazdırabililir mi ? yani üzerine geldiğinde de çalışacak haritayı açtığında da tüm isimleri görebilir misin ?
